apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: web
resources:
  - deployment-backend.yaml
  - deployment-frontend.yaml
  - service.yaml
  - ingress.yaml
  - pvc-uploads.yaml
  - postgres-init-scripts.yaml
  - imagerepository.yaml
  - imagepolicy.yaml
  - imageautomation.yaml
