apiVersion: v1
kind: Service
metadata:
  name: oppam-backend-service
  namespace: web
  labels:
    app: oppam-backend
spec:
  selector:
    app: oppam-backend
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: oppam-frontend-service
  namespace: web
  labels:
    app: oppam-frontend
spec:
  selector:
    app: oppam-frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: ClusterIP
