---
# Order Executor
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-executor
  namespace: trading
  labels:
    app: order-executor
    app.kubernetes.io/part-of: algo-trading-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-executor
  template:
    metadata:
      labels:
        app: order-executor
    spec:
      imagePullSecrets:
      - name: docker-hub-creds
      containers:
      - name: order-executor
        image: docker.io/sudhan03/algo-trading:order-executor-388e855
        imagePullPolicy: Always
        env:
        - name: ALPACA_API_KEY
          valueFrom:
            secretKeyRef:
              name: trading-secrets
              key: ALPACA_API_KEY
        - name: ALPACA_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: trading-secrets
              key: ALPACA_SECRET_KEY
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: trading-secrets
              key: DB_PASSWORD
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: trading-secrets
              key: REDIS_PASSWORD
        volumeMounts:
        - name: config
          mountPath: /app/config
        resources:
          requests:
            memory: "1Gi"
            cpu: "750m"
          limits:
            memory: "2Gi"
            cpu: "1500m"
      volumes:
      - name: config
        configMap:
          name: trading-config
