---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dagster
  namespace: trading
  labels:
    app: dagster
    app.kubernetes.io/part-of: algo-trading-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dagster
  template:
    metadata:
      labels:
        app: dagster
    spec:
      containers:
      - name: dagster
        image: docker.io/sudhan03/algo-trading:portfolio-tracker-latest
        imagePullPolicy: Always
        command: ["dagster", "dev", "-h", "0.0.0.0", "-p", "3000", "-f", "orchestrator/__init__.py"]
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: trading-secrets
        - configMapRef:
            name: trading-config
        volumeMounts:
        - name: dagster-home
          mountPath: /app/dagster_home
      volumes:
      - name: dagster-home
        emptyDir: {} # Ephemeral storage for now
---
apiVersion: v1
kind: Service
metadata:
  name: dagster
  namespace: trading
spec:
  selector:
    app: dagster
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dagster-ingress
  namespace: trading
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: dagster.sudharsana.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dagster
            port:
              number: 3000
