apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - pvc.yaml
  - deployment-timescaledb.yaml
  - deployment-redis.yaml
  - deployment-data-ingestion.yaml
  - deployment-strategy-engine.yaml
  - deployment-order-executor.yaml
  - deployment-portfolio-tracker.yaml
