apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog-backend-ingress
  namespace: web
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - api.sudharsana.dev
    secretName: blog-backend-tls
  rules:
  - host: api.sudharsana.dev
    http:
      paths:
      - path: /job-fit
        pathType: Prefix
        backend:
          service:
            name: job-fit-api-service
            port:
              number: 8000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: blog-backend-service
            port:
              number: 3001
