apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: blog-infra

resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  # Disabled to prevent conflict with main blog ingress
  # - ingress.yaml

images:
  - name: docker.io/sudhan03/blog-site-infra
    newTag: latest
