apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: orchestrator

resources:
  - namespace.yaml
  - rbac.yaml
  - pvc.yaml
  - configmap-env.yaml
  - configmap-instance.yaml
  - secret.yaml
  - deployment.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: unified-orchestrator
