apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog
  namespace: web
  annotations:
    # Add CORS headers for API routes
    traefik.ingress.kubernetes.io/custom-request-headers: "X-Forwarded-Proto:https"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - blog.sudharsana.dev
      secretName: blog-tls
  rules:
    - host: blog.sudharsana.dev
      http:
        paths:

          # Frontend routes - lower priority
          - path: /
            pathType: Prefix
            backend:
              service:
                name: blog
                port:
                  number: 80
